server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 路由策略id
      - id: test_route
        # 路由到的地址
        uri: https://wooo.io
        predicates:
        - Path=/about
logging:
  level:
    org.springframework.cloud.gateway: debug
