server:
  port: 9001
spring:
  application:
    name: tensquare-qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.24.114.73:3306/tensquare_qa?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: true
    database: mysql
# jwt
jwt:
  config:
    key: wocaonigedjnitamakendingbuzhidaoyanshishenmehahaha
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
  # 跨域访问
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true