server:
  port: 9000
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: true
    database: mysql
# rabbitmq:
#   host: 118.24.114.73
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
  # 跨域访问
  instance:
    prefer-ip-address: true
# jwt
jwt:
  config:
    key: wocaonigedjnitamakendingbuzhidaoyanshishenmehahaha
    ttl: 3600000
